# Generated by Django 5.0 on 2024-04-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('banner_image', models.ImageField(upload_to='spa_center/banner_images/')),
                ('spa_logo', models.ImageField(upload_to='spa_center/spa_logos/')),
                ('owner_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_contact', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gallery_image1', models.ImageField(upload_to='spa_center/gallery_images/')),
                ('gallery_image2', models.ImageField(upload_to='spa_center/gallery_images/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('services', models.ManyToManyField(related_name='spa_center_services', to='home.service')),
            ],
        ),
    ]
