# Generated by Django 5.0 on 2024-04-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacenter',
            name='keyword_search',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
