# Generated by Django 5.0 on 2024-04-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_spacenter_keyword_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacenter',
            name='keyword_search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
