# Generated by Django 5.0 on 2024-04-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_spacenter_keyword_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacenter',
            name='keyword_search',
        ),
    ]
